services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y httpie

script:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "development" ]; then
    export NUCLIO_LABEL="unstable";
    fi
  - if [ "$TRAVIS_TAG" != "" ]; then
    export NUCLIO_LABEL="$TRAVIS_TAG";
    fi
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - echo $NUCLIO_LABEL
  - if [ -n "$NUCLIO_LABEL" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io &&
    make build release &&
    if [ "$NUCLIO_LABEL" != "unstable" ]; then
    docker tag "quay.io/nuclio/prebaked-registry-nuclio:$NUCLIO_LABEL" quay.io/nuclio/prebaked-registry-nuclio:stable &&
    docker push quay.io/nuclio/prebaked-registry-nuclio:stable;
    fi
    fi
  - echo "Done."

deploy:
  provider: releases
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # user:email, read:org, repo_deployment, repo:status, write:repo_hook
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789`
  #      Note: If your project is on travis-ci.com you need to add the --pro flag like so:
  #      `travis encrypt 0123456789012345678901234567890123456789 --pro`
  # - Paste the output down here
  api_key:
     secure: "X/sFyZAUMiY9oBhIqnAHMhlb2eCqB3EiJl8obbFgidz9UdtTCHK7PZ6DWP6uA2KuI05/FLMGV6QypHhSiLkhQGtMJcJQPxOilmsOPkeXgs5YxMCxeG/9ciOAKWL7mE6AyhxHgGmb3iOYqXiQjjjD7GZ5P9C40tXeWOC5MwcpMHb2UwOTe8X6nPdVreknTORTyzO9XA3rr61o4Bs3lEHww2le/aCPCZod2Ey7PNZVF9n+1iUqqMPWx3RkZ/Owd7HiOH22/Lqt8rZ/M4Q8HBwpafuppMB9zrhnXb2psDLQNywLe9MF4AWx/zYfMB0fMXHVLlPsPfuI5wxrE7rgKOOlbclsM1l+CQcKMPVjeCUC6X9Vat8UtMWER6hQeQP8GGQFCG06R1UDypbTrBqxDCjvvFNI4W0nmAMhWAWIoM/muguOWHeDt6DFchUBlof91tXdDBcD4WhPMVWwrnyDNpVPSwoFpoRyirRFnOzeP47O+guCtIJiu7vbSQ18ZN6BL0Sw/b8NHgaC9OOWvqlFYm7SdBw3zl3NlR+aXh1mzD7E5nDKdHyxVMAoCyxWKVurhp79K51k+w5Q7xgDNf05K9XX14e6MEAtE3pJScnfhrzTzJXrNUw+6VzUKvf+MaPlaGqxayR3m/NJLmwvehHEjeV+gYyXTpnLp6Tobzd6xCBnSZ4="
  cleanup: false
  on:
    tags: true
