services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y httpie

script:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "development" ]; then
    export NUCLIO_LABEL="unstable";
    fi
  - if [ "$TRAVIS_TAG" != "" ]; then
    export NUCLIO_LABEL="$TRAVIS_TAG";
    fi
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - echo $NUCLIO_LABEL
  - if [ -n "$NUCLIO_LABEL" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" quay.io &&
    make build release &&
    if [ "$NUCLIO_LABEL" != "unstable" ]; then
    docker tag "quay.io/nuclio/prebaked-registry-nuclio:$NUCLIO_LABEL" quay.io/nuclio/prebaked-registry-nuclio:stable &&
    docker push quay.io/nuclio/prebaked-registry-nuclio:stable;
    fi
    fi
  - echo "Done."

deploy:
  provider: releases
  # - Create a `public_repo` GitHub token. Go to: https://github.com/settings/tokens/new
  # user:email, read:org, repo_deployment, repo:status, write:repo_hook
  # - Encrypt it: `travis encrypt 0123456789012345678901234567890123456789`
  #      Note: If your project is on travis-ci.com you need to add the --pro flag like so:
  #      `travis encrypt 0123456789012345678901234567890123456789 --pro`
  # - Paste the output down here
  api_key:
     secure: "Zey3b81VLQ4WQS8ok5RI8lNQ2ij+lv/Ny9WnUiVXSuP2Vrp6njytts7KjjdQkc1URD32/MQojmJDUO0F6KfOI3VzyyVZOylSkhtcNIlroKIkI4rcr1zeQuvxpK2h06konP3MEMRUtId/pWxfs2Udqi0wg/aY1eIUye/wggr0mB8zEZR7m1YM8BVaZDae7WHymIUUQUjGPVtb3oR9+NS6qC8gL3Is5/W0og29CeM1YOm5dvYMxu58U5OpNZfA+mKV97o1TBQIGE3PRz57obuXmZmHGU53xcVtTIwvqP+iftBvEXXuMc6AH6NeusFmGokoA6RG6+5T6HuuPjdaH3j/34YqtuDRU8aUp+Z7ZlU85ZM/peXCXLFQdFvcAui8ghLHZa4MCZqijhDC0NvdY3nWndugW2db+39Qp81rIILoysh3tfHqjXf2PCLekniMEOBnO52bx0XQDfV0Hu8+KkedEllCVe14NwZjLpbuv3ORGQM+Yw6quKafb7OzPhsp/EG/KX5PI85BWyzha9fkAcuT7Aw31at+FZqrivljqhzN3TleC9MKqYWQRmgrHtb3qtgnNIuNdqXg2icXlS4zQBbiDw0Dyw1RxspJ3nDTWlrDObM1/jF37EcX4PAi0zmqLzxJtiwFwj5TnbqMmb3Em1YJA1Du70ipMXE4ilDJpDzk6tg="
  cleanup: false
  on:
    tags: true
