services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - sudo apt-get install -y httpie

script:
  - bash <(curl -s https://codecov.io/bash)
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "development" ]; then
    export NUCLIO_LABEL="unstable";
    fi
  - if [ "$TRAVIS_TAG" != "" ]; then
    export NUCLIO_LABEL="$TRAVIS_TAG";
    fi
  - echo $TRAVIS_PULL_REQUEST
  - echo $TRAVIS_BRANCH
  - echo $NUCLIO_LABEL
  - if [ -n "$NUCLIO_LABEL" ]; then
    echo "$DOCKER_PASSWORD" | docker login -u="$DOCKER_USERNAME" --password-stdin quay.io &&
    make build release &&
    if [ "$NUCLIO_LABEL" != "unstable" ]; then
    docker tag "quay.io/nuclio/prebaked-registry-nuclio:$NUCLIO_LABEL" quay.io/nuclio/prebaked-registry-nuclio:stable &&
    docker push quay.io/nuclio/prebaked-registry-nuclio:stable;
    fi
    fi
  - echo "Done."

deploy:
  provider: releases
  api_key:
    secure: XYb8aOndiae7AoLyZU2e4s4GKKyoJjjW8tA+gG0HHD6AhqbaaSx6IofwNbQqOhM0iGOTWeeG3SaW34MPRcjV3FX0fYO8lW2GAynXT6Td5uhJmPtmk/msrfdLlCVYhQ42DoWjvtWwaejJRZCYHNlhAwH6c/peSO7KqN0QaRABfO4CK6Npvt9JMo+hCfxnUmaVBzkbtfXIrBlxkXxVOGn/geUzf+2qpnMw85WMIN8RIXedNBe0UBkBasPJA5hKadckMKDCaIbiQ8KsOF2HK7IGwg/goTMfshuOZn/f8aCC+D5lyCQD3bkuHJqrj+HYCVHalAeESXJGmSHr/xmV+XQ9RoxdSUaO2TBU4r+WPPM1JsNNAvQe4zxEaVXOu41bRbZnccxwCHhPcKwT+KD7IniJMUdRkTadGPx+yZoMGwxtGK6elDyr3yzzYRfjBIcfecaPVifny51bRxWpGwcaoWP0qew86vqMcCz9dQBZUvKA/+zdcKXZHvqbouh+Iv79z7BVaW7aTmcsIhn7miqH5qIOnfJUsZiBAAY5EX7FpXMtSx9cpna+vKsvtRtSnywLsLDiLAPLWE0muTDPDksDsmTT0AvHQENv0bd5U0qnTlaR2Q31Q2e8WY0y7DZrYgruNGTvVtwrrAv4KvBHjO0GJya4NvnZB37yMFTKJouZU/o8qm4=
  cleanup: false
  on:
    tags: true
